name: 'Moulti checks (OpenBSD)'
on:
  push:
    branches:
    - devel
jobs:
  openbsdchecks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: OpenBSD
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add python py3-pip bash git
        run: |
          set -e
          python3.12 --version
          pip --version
          python3.12 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -e .[bsd-ci]
          # no ruff, no ruff check
          mypy src/moulti
          pylint src/moulti
          # This runs all tests except:
          # - test_diff_with_delta (requires delta 0.18.x)
          pytest -v
